name: Build Android APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
      ANDROID_HOME: ${{ github.workspace }}/android-sdk
      PATH: ${{ github.workspace }}/android-sdk/cmdline-tools/latest/bin:${{ github.workspace }}/android-sdk/platform-tools:${{ github.workspace }}/android-sdk/build-tools/33.0.0:$PATH

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          python3-setuptools \
          python3-virtualenv \
          openjdk-17-jdk \
          unzip \
          git \
          build-essential \
          zip \
          zlib1g-dev

    - name: Install Buildozer and dependencies
      run: |
        python3 -m pip install --upgrade pip setuptools wheel
        pip install buildozer cython

    - name: Setup Android SDK
      run: |
        mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
        cd $ANDROID_SDK_ROOT/cmdline-tools
        curl -o commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip -q commandlinetools.zip
        mv cmdline-tools latest
        rm commandlinetools.zip

    - name: Accept Android SDK licenses
      run: |
        yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses

    - name: Install Android SDK packages
      run: |
        $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.0" "ndk;25.1.8937393"

    - name: Build APK with Buildozer
      run: |
        buildozer android clean
        buildozer android debug deploy run
      env:
        ANDROIDSDK: $ANDROID_SDK_ROOT
        ANDROID_NDK_HOME: $ANDROID_SDK_ROOT/ndk/25.1.8937393
        ANDROID_HOME: $ANDROID_SDK_ROOT

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: bin/*.apk
