name: Build Android APK with Buildozer

on:
  push:
  pull_request:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    env:
      ANDROID_HOME: $HOME/android-sdk
      ANDROID_SDK_ROOT: $HOME/android-sdk
      PATH: $HOME/.local/bin:$HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools:$PATH

    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v4

      - name: 🧰 Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip git unzip zip tar curl openjdk-17-jdk \
            libffi-dev libssl-dev libsqlite3-dev libpng-dev \
            libjpeg-dev zlib1g-dev libgl1-mesa-dev libgles2-mesa-dev \
            libgtk-3-dev libnss3 libxss1 libasound2t64 libbz2-dev libc6-dev \
            libncurses6

      - name: 📦 Upgrade pip & install Python packages
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          pip install buildozer cython kivy numpy scikit-learn

      - name: 📦 Install Android SDK Commandline Tools
        run: |
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          cd $ANDROID_SDK_ROOT/cmdline-tools
          curl -o tools.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip tools.zip
          rm tools.zip
          mv cmdline-tools latest

      - name: ✅ Accept Android SDK Licenses
        run: |
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses

      - name: 📥 Install Android SDK packages
        run: |
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT \
            "platform-tools" "platforms;android-33" "build-tools;33.0.0"

      - name: 🚧 Build APK with Buildozer (with retry logic)
        run: |
          buildozer -v android debug || (sleep 30 && buildozer -v android debug) || (sleep 60 && buildozer -v android debug)

      - name: 📂 List APKs
        run: ls -lh bin || true

      - name: ⬆ Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: slotprediksnapp-apk
          path: bin/*.apk
