name: Android Build

on:
  push:
    branches:
      - main  # Promijenite na vašu glavnu granu ako nije 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip python3-setuptools python3-wheel
        pip install --upgrade pip
        pip install buildozer cython

    - name: Run Buildozer
      run: |
        buildozer init
        buildozer -v android debug
