name: Build Android APK with Buildozer

on:
  push:
  pull_request:

jobs:
  build-apk:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip \
            git \
            unzip \
            openjdk-17-jdk \
            libncurses5 \
            libstdc++6 \
            zlib1g-dev \
            libffi-dev \
            libssl-dev \
            libsqlite3-dev \
            libjpeg-dev \
            libandroid-support-dev \
            autoconf \
            libtool \
            build-essential \
            tar \
            wget

      - name: Upgrade pip & install Python packages
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          pip3 install cython buildozer kivy numpy scikit-learn

      - name: Install Android SDK Command Line Tools
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O tools.zip
          unzip -q tools.zip
          rm tools.zip
          mv cmdline-tools latest
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH

      - name: Accept licenses and install Android SDK components
        run: |
          yes | sdkmanager --sdk_root=$HOME/android-sdk --licenses
          sdkmanager --sdk_root=$HOME/android-sdk \
            "platform-tools" \
            "platforms;android-33" \
            "build-tools;33.0.0"

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: slotprediksnapp-apk
          path: bin/*.apk
