name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            zip unzip openjdk-17-jdk \
            python3-pip python3-setuptools python3-wheel \
            libffi-dev libssl-dev libsqlite3-dev \
            libjpeg-dev zlib1g-dev \
            libncurses6 libstdc++6 clang

      - name: Install Buildozer and dependencies
        run: |
          pip install --upgrade pip
          pip install cython
          pip install buildozer

      - name: Create Android SDK folders
        run: |
          mkdir -p ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest

      - name: Download Android command line tools
        run: |
          cd ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest
          curl -o sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip sdk-tools.zip
          rm sdk-tools.zip

      - name: Accept Android SDK licenses
        run: yes | ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Install Android SDK packages
        run: |
          ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager \
            "platform-tools" \
            "platforms;android-34" \
            "build-tools;34.0.0" \
            "ndk;25.2.9519653"

      - name: Build the APK with Buildozer
        run: |
          buildozer android debug
