name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zip unzip openjdk-17-jdk python3-pip
          pip install --upgrade pip
          pip install buildozer cython

      - name: Install Android SDK manually
        run: |
          mkdir -p $HOME/android-sdk
          cd $HOME
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d android-sdk/
          mv android-sdk/cmdline-tools android-sdk/cmdline-tools-temp
          mkdir -p android-sdk/cmdline-tools/latest
          mv android-sdk/cmdline-tools-temp/* android-sdk/cmdline-tools/latest/

      - name: Set environment variables
        run: |
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH
          echo "$HOME/android-sdk/emulator" >> $GITHUB_PATH

      - name: Install SDK components
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platforms;android-34" "build-tools;36.0.0" "ndk;25.2.9519653"

      - name: Build APK
        run: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: G4mbler-debug-apk
          path: bin/*.apk
