name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y libffi-dev libssl-dev libjpeg-dev libfreetype6-dev libncurses6 unzip openjdk-17-jdk wget zip

      - name: Install Buildozer and Cython
        run: |
          pip install --upgrade pip
          pip install cython
          pip install buildozer

      - name: Download Android cmdline-tools
        run: |
          mkdir -p ~/.buildozer/android/platform/android-sdk/cmdline-tools
          cd ~/.buildozer/android/platform/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip
          mv cmdline-tools latest

      - name: Create symlink tools -> cmdline-tools/latest (compatibility)
        run: |
          cd ~/.buildozer/android/platform/android-sdk
          ln -sf cmdline-tools/latest tools

      - name: Set ANDROID_SDK_ROOT environment variable
        run: echo "ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk" >> $GITHUB_ENV

      - name: Accept Android SDK licenses
        run: yes | $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Install SDK packages
        run: |
          $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager \
            "platforms;android-31" \
            "build-tools;31.0.0" \
            "ndk;25.2.9519653" \
            "platform-tools" \
            "tools"

      - name: Build APK with Buildozer
        run: buildozer android debug
