name: Build Android APK with Buildozer

on:
  push:
  pull_request:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip \
            git \
            unzip \
            openjdk-17-jdk \
            wget \
            tar \
            zip \
            libncurses5 \
            libffi-dev \
            libssl-dev \
            libsqlite3-dev \
            libpng-dev \
            libjpeg-dev \
            zlib1g-dev \
            libgl1-mesa-dev \
            libgles2-mesa-dev \
            libgtk-3-dev \
            libnss3 \
            libxss1 \
            libasound2 \
            libbz2-dev \
            libc6-dev

      - name: Upgrade pip & install Python dependencies
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          pip install --upgrade buildozer Cython numpy scikit-learn kivy

      - name: Download and install Android SDK Command Line Tools
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O sdk.zip
          unzip sdk.zip
          rm sdk.zip
          mv cmdline-tools latest

      - name: Accept Android SDK licenses and install SDK components
        run: |
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT \
            "platform-tools" \
            "platforms;android-33" \
            "build-tools;33.0.0"

      - name: Set environment variables
        run: |
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH

      - name: Build APK with Buildozer (with retry)
        run: |
          buildozer android debug

      - name: List APKs
        run: ls -lh bin || true

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: slotprediksnapp-apk
          path: bin/*.apk
