name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install build dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          zip unzip openjdk-17-jdk \
          python3-pip python3-setuptools python3-wheel \
          libffi-dev libssl-dev libsqlite3-dev \
          libjpeg-dev zlib1g-dev \
          libncurses5 libstdc++6 clang

    - name: Install pip packages
      run: |
        python3 -m pip install --upgrade pip
        pip install buildozer cython

    - name: Create SDK directories
      run: |
        mkdir -p $HOME/android-sdk/cmdline-tools
        cd $HOME/android-sdk/cmdline-tools
        curl -o commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
        unzip -q commandlinetools.zip
        rm commandlinetools.zip
        mv cmdline-tools latest

    - name: Add Android SDK to PATH
      run: echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH

    - name: Accept SDK licenses
      run: yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses

    - name: Install Android SDK components
      run: |
        $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager \
          "platform-tools" \
          "platforms;android-34" \
          "build-tools;34.0.0" \
          "ndk;25.2.9519653"

    - name: Build APK
      run: |
        pip install --upgrade buildozer
        buildozer android debug
