name: Build Android APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_API: 31
      ANDROID_MINAPI: 21
      ANDROID_SDK_VERSION: 24
      ANDROID_NDK_VERSION: 25b

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          git \
          tar
          python3-pip \
          openjdk-17-jdk \
          unzip \
          libncurses6

    - name: Upgrade pip and install buildozer & p4a
      run: |
        pip install --upgrade pip
        pip install --upgrade buildozer python-for-android

    - name: Initialize Android SDK
      run: |
        buildozer android sdk

    - name: Accept all Android SDK licenses
      run: |
        yes | ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses || true

    - name: Clean previous build artifacts
      run: buildozer android clean

    - name: Build APK
      run: buildozer -v android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: g4mbler-apk
        path: bin/*.apk
