name: Build Android APK with Buildozer

on:
  push:
  pull_request:

jobs:
  build-apk:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip \
            git \
            unzip \
            zip \
            openjdk-17-jdk \
            libffi-dev \
            libssl-dev \
            libjpeg-dev \
            libncurses5 \
            libncursesw5 \
            libtinfo5 \
            build-essential \
            ccache \
            tar \
            wget

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install --upgrade setuptools wheel
          pip install --upgrade buildozer

      - name: Set up Android SDK
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk/cmdline-tools
          curl -o commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip -q commandlinetools.zip
          rm commandlinetools.zip
          mv cmdline-tools latest

      - name: Accept Android licenses and install required packages
        run: |
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH
          yes | sdkmanager --sdk_root=${ANDROID_SDK_ROOT} --licenses
          sdkmanager --sdk_root=${ANDROID_SDK_ROOT} \
            "platform-tools" \
            "platforms;android-33" \
            "build-tools;33.0.0" \
            "cmake;3.22.1"

      - name: Set environment variables
        run: |
          echo "ANDROIDSDK=$HOME/android-sdk" >> $GITHUB_ENV
          echo "PATH=$HOME/android-sdk/platform-tools:$HOME/android-sdk/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV

      - name: Copy icons folder (include PNGs)
        run: |
          mkdir -p icons
          
      - name: Build APK with Buildozer
        run: |
          buildozer android debug

      - name: List APKs
        run: ls -lh bin || true

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: slotprediksnapp-apk
          path: bin/*.apk
