name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Install tar if missing
        run: |
          sudo apt-get update
          sudo apt-get install -y tar

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            libncurses6 \
            libstdc++6 \
            python3-pip \
            python3-setuptools \
            python3-wheel \
            ccache \
            libffi-dev \
            libssl-dev \
            zlib1g-dev \
            libjpeg-dev

          pip install --upgrade pip
          pip install --user --upgrade buildozer cython

      - name: Set environment variables
        run: |
          echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV
          echo "ANDROIDSDK=$HOME/.buildozer/android/platform/android-sdk" >> $GITHUB_ENV
          echo "ANDROIDNDK=$HOME/.buildozer/android/platform/android-ndk-r25b" >> $GITHUB_ENV
          echo "ANDROIDAPI=31" >> $GITHUB_ENV
          echo "ANDROIDMINAPI=21" >> $GITHUB_ENV

      - name: Build APK
        run: |
          buildozer android debug
