name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zip unzip openjdk-17-jdk python3-pip wget
          pip install --upgrade pip
          pip install buildozer cython

      - name: Install Android SDK command line tools
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d android-sdk/cmdline-tools-temp
          mkdir -p android-sdk/cmdline-tools/latest
          mv android-sdk/cmdline-tools-temp/* android-sdk/cmdline-tools/latest/
          rm cmdline-tools.zip

      - name: Set environment variables for Android SDK
        run: |
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH
          echo "$HOME/android-sdk/emulator" >> $GITHUB_PATH

      - name: Accept all Android SDK licenses
        run: yes | sdkmanager --licenses

      - name: Install required Android SDK packages
        run: |
          sdkmanager "platforms;android-34"
          sdkmanager "build-tools;34.0.0"
          sdkmanager "platform-tools"
          sdkmanager "ndk;25.2.9519653"

      - name: Set Android environment variables used by Buildozer
        run: |
          echo "ANDROIDAPI=34" >> $GITHUB_ENV
          echo "ANDROIDMINAPI=21" >> $GITHUB_ENV
          echo "ANDROIDNDK=25.2.9519653" >> $GITHUB_ENV
          echo "ANDROID_NDK_ROOT=$HOME/android-sdk/ndk/25.2.9519653" >> $GITHUB_ENV
          echo "ANDROID_NDK=$HOME/android-sdk/ndk/25.2.9519653" >> $GITHUB_ENV

      - name: Verify SDK and NDK installation folders
        run: |
          ls -l $HOME/android-sdk/platforms/android-34
          ls -l $HOME/android-sdk/build-tools/34.0.0
          ls -l $HOME/android-sdk/ndk/25.2.9519653

      - name: Link SDK folders for Buildozer compatibility
        run: |
          mkdir -p /home/runner/.buildozer/android/platform
          ln -sf $HOME/android-sdk /home/runner/.buildozer/android/platform/android-sdk
          mkdir -p /home/runner/.buildozer/android/platform/android-sdk/tools/bin
          ln -sf $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager /home/runner/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager

      - name: Clean previous build data
        run: rm -rf .buildozer

      - name: Show Buildozer version
        run: buildozer --version

      - name: Build APK (verbose)
        run: buildozer -v android debug
