name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    env:
      ANDROID_SDK_ROOT: ${{ github.workspace }}/.buildozer/android/platform/android-sdk
      ANDROID_NDK_HOME: ${{ github.workspace }}/.buildozer/android/platform/android-ndk-r25b
      ANDROID_API: 31
      ANDROID_MIN_API: 21
      JAVA_HOME: /usr/lib/jvm/temurin-17-jdk-amd64
      PATH: /usr/lib/jvm/temurin-17-jdk-amd64/bin:${{ github.workspace }}/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin:$PATH

    steps:
      - uses: actions/checkout@v3

      - name: Update apt and install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libncurses6 libstdc++6 libffi-dev libssl-dev openjdk-17-jdk unzip

      - name: Setup Python and install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install buildozer cython kivy numpy 

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: bin/*.apk
